package com.tuanhust.activityservice.entity.enums;

public enum ActionType {
    //owner action
    CREATE_PROJECT,
    UPDATE_PROJECT,
    DELETE_PROJECT,
    ARCHIVE_PROJECT,
    RESTORE_PROJECT,

    ADD_MEMBER,
    DELETE_MEMBER,
    UPDATE_ROLE,

    //member action
    CREATE_TASK,
    UPDATE_TASK,
    DELETE_TASK,
    MOVE_TASK,
    ARCHIVE_TASK,
    RESTORE_TASK,

    COMPLETE_TASK,
    INCOMPLETE_TASK,

    ADD_ASSIGNEE,
    DELETE_ASSIGNEE,

    ADD_TASK_LABEL,
    DELETE_TASK_LABEL,

    ADD_COMMENT,
    UPDATE_COMMENT,
    DELETE_COMMENT,

    ADD_CHECKLIST,
    UPDATE_CHECKLIST,
    DELETE_CHECKLIST,
}
