package com.tuanhust.coreservice.dto;

public enum ActionType {
    //owner action
    CREATE_PROJECT,
    UPDATE_PROJECT,
    ARCHIVE_PROJECT,
    RESTORE_PROJECT,
    DELETE_PROJECT,

    ADD_MEMBER,
    DELETE_MEMBER,
    UPDATE_ROLE,

    ADD_LABEL,
    DELETE_LABEL,
    UPDATE_LABEL,

    ADD_BOARD_COLUMN,
    DELETE_BOARD_COLUMN,
    UPDATE_BOARD_COLUMN,
    MOVE_BOARD_COLUMN,
    ARCHIVE_BOARD_COLUMN,
    RESTORE_BOARD_COLUMN,

    //member action
    CREATE_TASK,
    UPDATE_TASK,
    DELETE_TASK,
    MOVE_TASK,
    ARCHIVE_TASK,
    RESTORE_TASK,

    COMPLETE_TASK,
    INCOMPLETE_TASK,

    ADD_LABEL_TASK,
    DELETE_LABEL_TASK,

    ADD_MEMBER_TASK,
    DELETE_MEMBER_TASK,

    ADD_COMMENT,
    UPDATE_COMMENT,
    DELETE_COMMENT,

    ADD_CHECKLIST,
    COMPLETE_CHECKLIST,
    INCOMPLETE_CHECKLIST,
    UPDATE_CHECKLIST,
    DELETE_CHECKLIST, INVITE_MEMBER,
}
